services:
  backup_restore:
    build: ./backup_restore/
    environment:
      - POSTGRES_HOST=wikijs_db
      - POSTGRES_USER=$POSTGRES_USER
      - PGPASSWORD=$POSTGRES_PASSWORD
      - SQLITE_FILE=/db/db.sqlite
      - KANBAN_DB=/kanban/database.json
    volumes:
      - bibin_data:/db
      - kanban_data:/kanban
      - /home/ubuntu/.ssh:/ssh_host

  wallabag:
    image: wallabag/wallabag
    volumes:
     - wallabag_data:/var/www/wallabag/data
     - wallabag_images:/var/www/wallabag/web/assets/images
    environment:
      - SYMFONY__ENV__DOMAIN_NAME=https://wall.marache.net/

  bibin:
    build: ./bibin/
    restart: unless-stopped
    volumes:
      - bibin_data:/db
    environment:
      - ROCKET_SECRET_KEY=$ROCKET_SECRET_KEY
      - ROCKET_PASSWORD=$ROCKET_PASSWORD
      - ROCKET_MAX_ENTRIES=$ROCKET_MAX_ENTRIES
      - ROCKET_ID_LENGTH=$ROCKET_ID_LENGTH
      - ROCKET_DATABASE_FILE=/db/db.sqlite
      - ROCKET_PREFIX=$ROCKET_PREFIX
      - ROCKET_ADDRESS=0.0.0.0

  faas:
    build: ./faas/
    restart: unless-stopped
    environment:
      - ROCKET_ADDRESS=0.0.0.0
      - ROCKET_URL_PREFIX=https://faas.marache.net/

  caddy:
    build: ./caddy/
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./caddy/Caddyfile:/etc/caddy/Caddyfile
      - caddy_data:/data
      - caddy_config:/config
    environment:
      - GOOGLE_CLIENT_ID=$GOOGLE_CLIENT_ID
      - GOOGLE_CLIENT_SECRET=$GOOGLE_CLIENT_SECRET
      - JWT_SHARED_KEY=$JWT_SHARED_KEY
      - USER_EMAIL=$USER_EMAIL

  wikijs_db:
    image: postgres:11-alpine
    restart: unless-stopped
    environment:
      POSTGRES_DB: $POSTGRES_DB
      POSTGRES_PASSWORD: $POSTGRES_PASSWORD
      POSTGRES_USER: $POSTGRES_USER
    volumes:
      - wikijs_data:/var/lib/postgresql/data
  wikijs:
    image: requarks/wiki:2
    restart: unless-stopped
    depends_on:
      - wikijs_db
    environment:
      DB_TYPE: postgres
      DB_HOST: wikijs_db
      DB_PORT: 5432
      DB_USER: $POSTGRES_USER
      DB_PASS: $POSTGRES_PASSWORD
      DB_NAME: $POSTGRES_DB

  kanban:
    container_name: kanban
    build: ./vibe-kanban
    volumes:
      - kanban_data:/app/data
    environment:
      - DATA_DIR=/app/data
    restart: unless-stopped

volumes:
  caddy_data:
    external: true
  caddy_config:
  bibin_data:
    external: true
  wikijs_data:
    external: true
  wallabag_data:
    external: true
  kanban_data:
    external: true
  wallabag_images:
    external: true
