version: "3.9"

services:
  backup_restore:
    build: ./backup_restore/
    environment:
      - POSTGRES_HOST=wikijs_db
      - POSTGRES_USER=$POSTGRES_USER
      - S3_BUCKET=$S3_BUCKET
      - AWS_ACCESS_KEY_ID=$AWS_ACCESS_KEY_ID
      - AWS_SECRET_ACCESS_KEY=$AWS_SECRET_ACCESS_KEY
      - AWS_DEFAULT_REGION=$AWS_DEFAULT_REGION
      - PGPASSWORD=$POSTGRES_PASSWORD
      - SQLITE_FILE=/db/db.sqlite
    volumes:
      - bibin_data:/db

  bibin:
    build: ./bibin/
    restart: unless-stopped
    volumes:
      - bibin_data:/db
    environment:
      - ROCKET_SECRET_KEY=$ROCKET_SECRET_KEY
      - ROCKET_PASSWORD=$ROCKET_PASSWORD
      - ROCKET_MAX_ENTRIES=$ROCKET_MAX_ENTRIES
      - ROCKET_ID_LENGTH=$ROCKET_ID_LENGTH
      - ROCKET_DATABASE_FILE=/db/db.sqlite
      - ROCKET_PREFIX=$ROCKET_PREFIX
      - ROCKET_ADDRESS=0.0.0.0
  caddy:
    image: caddy:2-alpine
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - caddy_data:/data
      - caddy_config:/config

  wikijs_db:
    image: postgres:11-alpine
    restart: unless-stopped
    environment:
      POSTGRES_DB: $POSTGRES_DB
      POSTGRES_PASSWORD: $POSTGRES_PASSWORD
      POSTGRES_USER: $POSTGRES_USER
    volumes:
      - wikijs_data:/var/lib/postgresql/data
  wikijs:
    image: requarks/wiki:2
    restart: unless-stopped
    depends_on:
      - wikijs_db
    environment:
      DB_TYPE: postgres
      DB_HOST: wikijs_db
      DB_PORT: 5432
      DB_USER: $POSTGRES_USER
      DB_PASS: $POSTGRES_PASSWORD
      DB_NAME: $POSTGRES_DB
volumes:
  caddy_data:
    external: true
  caddy_config:
  bibin_data:
    external: true
  wikijs_data:
    external: true
